#S10P31S208-123 feat: ocr submodule  test

diff --git a/OCR/jenkinsfile b/OCR/jenkinsfile
--- a/OCR/jenkinsfile
+++ b/OCR/jenkinsfile
@@ -80,26 +80,22 @@ pipeline {
                     sh 'pwd'
                     sh 'ls -al'
 
-                    // 현재 디렉토리 위치와 파일 목록 출력을 backend 디렉토리 내에서 실행
-                    dir('backend') {
-                        sh 'pwd'  // 현재 디렉토리 위치 출력
-                        sh 'ls -al'  // 디렉토리 내의 파일 목록 출력
+                 
 
-                        // docker-compose가 설치되어 있는지 확인하고, 없으면 설치
-                        sh '''
-                        if ! command -v docker-compose &> /dev/null
-                        then
-                            echo "docker-compose not found, installing..."
-                            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
-                            sudo chmod +x /usr/local/bin/docker-compose
-                        else
-                            echo "docker-compose is already installed."
-                        fi
-                        '''
+                    // docker-compose가 설치되어 있는지 확인하고, 없으면 설치
+                    sh '''
+                    if ! command -v docker-compose &> /dev/null
+                    then
+                        echo "docker-compose not found, installing..."
+                        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                        sudo chmod +x /usr/local/bin/docker-compose
+                    else
+                        echo "docker-compose is already installed."
+                    fi
+                    '''
 
-                        // Docker Compose를 사용하여 서비스 빌드
-                        sh 'docker-compose -f docker-compose.yml build'
-                    }
+                    // Docker Compose를 사용하여 서비스 빌드
+                    sh 'docker-compose -f docker-compose.yml build'
                 }
             }
         }
